"""empty message

Revision ID: 17b64b20f2dd
Revises: 5183e64dbb69
Create Date: 2014-08-06 19:57:43.538000

"""

# revision identifiers, used by Alembic.
revision = '17b64b20f2dd'
down_revision = '5183e64dbb69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
