"""empty message

Revision ID: 1852ae49ecb1
Revises: None
Create Date: 2014-08-06 18:51:51.481000

"""

# revision identifiers, used by Alembic.
revision = '1852ae49ecb1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
