"""empty message

Revision ID: 2da3b14330cd
Revises: 3b0869a0cb02
Create Date: 2014-08-08 21:00:12.546000

"""

# revision identifiers, used by Alembic.
revision = '2da3b14330cd'
down_revision = '3b0869a0cb02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('like', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'like')
    ### end Alembic commands ###
