"""empty message

Revision ID: 5183e64dbb69
Revises: c247c88caec
Create Date: 2014-08-06 19:54:43.415000

"""

# revision identifiers, used by Alembic.
revision = '5183e64dbb69'
down_revision = 'c247c88caec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
