"""empty message

Revision ID: c247c88caec
Revises: 1852ae49ecb1
Create Date: 2014-08-06 19:29:46.891000

"""

# revision identifiers, used by Alembic.
revision = 'c247c88caec'
down_revision = '1852ae49ecb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
